# Generated by Django 3.2.6 on 2021-09-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productLink',
            field=models.URLField(default='https://www.google.ca/'),
            preserve_default=False,
        ),
    ]
